/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.iceberg.sedona.scala-application-conventions")
}

application {
    // Define the main class for the application.
    mainClass.set("org.apache.iceberg.sedona.app.App")
}
