/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package org.apache.iceberg.sedona.app

import org.apache.commons.text.WordUtils
import org.apache.iceberg.sedona.list.LinkedList

object App {
  def main(args: Array[String]): Unit = {
    val linkedList = new LinkedList
    val message = MessageUtils.getMessage()
    message.split("\\s+").foreach(linkedList.add)
    println(linkedList.size())
    println(WordUtils.capitalize(message))
  }
}
