/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("org.apache.iceberg.sedona.scala-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
    compileOnly("org.scala-lang:scala-library")
    compileOnly("org.apache.spark:spark-sql_2.12:3.3.0")
}
