import gradle.kotlin.dsl.accessors._3729b0f936a9389bcd6a878a40c67b60.implementation

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("org.apache.iceberg.sedona.scala-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

dependencies {
    testImplementation("org.apache.iceberg:iceberg-hive-metastore")
    testImplementation("org.apache.iceberg:iceberg-spark-extensions-3.3_2.12")
    testImplementation("org.apache.spark:spark-hive_2.12:3.3.0") {
        exclude("org.apache.avro", "avro")
        exclude("org.apache.arrow")
        exclude("org.apache.parquet")
        // to make sure io.netty.buffer only comes from project(':iceberg-arrow')
        exclude("io.netty", "netty-buffer")
        exclude("org.roaringbitmap")
    }
}