import gradle.kotlin.dsl.accessors._33817daed111f64b7d3684b28a3ff45d.testImplementation

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.9")

        implementation("org.scala-lang:scala-library:2.12.15")
        implementation("org.locationtech.jts:jts-core:1.19.0")
        implementation("org.apache.spark:spark-sql_2.12:3.3.0")
        implementation("org.apache.spark:spark-hive_2.12:3.3.0")
        implementation("org.apache.sedona:sedona-sql-3.0_2.12:1.2.1-incubating")
        implementation("org.apache.iceberg:iceberg-spark-3.3_2.12:0.15.0-gd-SNAPSHOT")
        implementation("org.apache.iceberg:iceberg-spark-extensions-3.3_2.12:0.15.0-gd-SNAPSHOT")
        implementation("org.apache.iceberg:iceberg-hive-metastore:0.15.0-gd-SNAPSHOT")
    }

    // Use Scala 2.12 in our library project
    implementation("org.scala-lang:scala-library")

    // Common dependencies of our project
    implementation("org.locationtech.jts:jts-core")
    implementation("org.apache.sedona:sedona-sql-3.0_2.12")
    implementation("org.apache.iceberg:iceberg-spark-3.3_2.12")
    implementation("org.apache.spark:spark-sql_2.12")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
