import gradle.kotlin.dsl.accessors._33817daed111f64b7d3684b28a3ff45d.testImplementation

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("org.apache.iceberg.sedona.scala-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}
