/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package org.apache.iceberg.sedona.utilities

import org.apache.iceberg.sedona.list.LinkedList

object StringUtils {
    def join(source: LinkedList): String = {
        JoinUtils.join(source)
    }

    def split(source: String): LinkedList = {
        SplitUtils.split(source)
    }
}
